name: stateless_server
description: A Dart stateless server framework.
version: 1.0.0

environment:
  sdk: ^3.2.2

dependencies:
  crypto: ^3.0.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  uuid: ^4.2.1

dev_dependencies:
  lints: ^3.0.0
